stages:
  - test

services:
  - name: redis:7-alpine
    alias: redis
    command: ["sh", "-c", "redis-server --port 8200"]

variables:
  MYSQL_ROOT_PASSWORD: zjlab2022root
  MYSQL_USER: zjlab
  MYSQL_PASSWORD: zjlab2022
  MYSQL_DATABASE: zj_brain_science_platform
  TZ: Asia/Shanghai

before_script:
  # 启动 MySQL 容器并映射端口
  - docker run -d -p 8800:3306 --name mysql-container -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -e MYSQL_USER=$MYSQL_USER -e MYSQL_PASSWORD=$MYSQL_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -e TZ=$TZ caitaozjlab/zjbs-database:latest
  # 启动 Redis 容器并映射端口
  - docker run -d -p 8200:6379 --name redis-container redis:7-alpine redis-server --port 6379

pytest:
  stage: test
  image: python:3.8
  script:
    - apt-get update -y
    - apt-get install -y python3-pip
    - pip install pytest
    - pytest tests/
  services:
    - name: redis:7-alpine
      alias: redis
    - name: mysql
      alias: mysql