stages:
  - test
  

services:
  - name: redis:7-alpine
    alias: redis
    command: ["sh", "-c", "redis-server --port 8200"]    
    
  - name: caitaozjlab/zjbs-database:latest
    alias: datasbase
    variables:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai

    command: ["sh", "-c", "docker-entrypoint.sh mysqld --skip-networking=false --port=8800"]

  - name: quay.io/keycloak/keycloak:latest
    alias: keycloak
    variables:
      EYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: test
      KEYCLOAK_CLIENT_ID: dataplatform
      KEYCLOAK_CLIENT_SECRET: 0p9jizKBOrahVzZKzhgW

install_dependencies:
  tags: 
  stage: test
  image: python:3.11
  before_script:
    
    - pip install poetry  # 安装 Poetry
    - pip install --index-url https://pypi.tuna.tsinghua.edu.cn/simple poetry
    - mkdir -p "${HOME}/log" "${HOME}/file"
  cache:
    paths:
      - .cache/pypoetry
  script:
    - poetry install --without dev 
    - DEBUG_MODE=on LOG_ROOT="${HOME}/log" FILE_ROOT="${HOME}/file" poetry run alembic upgrade head

