stages:
  - test
  - install
image: ubuntu-latest
services:
  - name: redis:7-alpine
    alias: redis
    command: ["sh", "-c", "redis-server --port 8200"]    
    
  - name: caitaozjlab/zjbs-database:latest
    alias: mysql
    command: ["sh", "-c", "docker-entrypoint.sh mysqld --skip-networking=false --port=8800"]

variables:
  MYSQL_ROOT_PASSWORD: zjlab2022root
  MYSQL_USER: zjlab
  MYSQL_PASSWORD: zjlab2022
  MYSQL_DATABASE: zj_brain_science_platform
  TZ: Asia/Shanghai
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - apt-get update -y && apt-get install -y python3-pip
  - pip install pipx
  - pipx install poetry

install_dependencies:
  stage: install
  image: python:3.11
  script:
    - poetry install --without dev
migrate_database:
  stage: migrate
  image: python:3.11
  script:
    - mkdir -p "${HOME}/log" "${HOME}/file"
    - poetry run alembic upgrade head
