version: "3"
services:
  backend:
    build: .
    ports:
      - "1919:80"
    environment:
      DATABASE_URL: mysql://zjlab:zjlab2022@database:3306/zj_brain_science_platform
      DATABASE_CONFIG: '{}'
    volumes:
      - ./log/app:/code/log/app
    restart: always
    networks:
      - local-network
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    restart: always
    networks:
      - local-network

networks:
  local-network:
    driver: bridge