version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile/backend.Dockerfile
    ports:
      - "1919:80"
    environment:
      DATABASE_URL: mysql+pymysql://zjlab:zjlab2022@database:3306/zj_brain_science_platform
      DATABASE_CONFIG: '{}'
    volumes:
      - ~/log/ZJBrainSciencePlatform/app:/root/log/ZJBrainSciencePlatform/app
    restart: always
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: dockerfile/database.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai
    ports:
      - "8100:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ~/mysql/ZJBrainSciencePlatform/data:/var/lib/mysql
      - ~/log/ZJBrainSciencePlatform/mysql:/var/log/mysql
    restart: always

  alembic:
    build:
      context: .
      dockerfile: dockerfile/alembic.Dockerfile
    restart: "no"
    volumes:
      - ./alembic:/code/alembic
      - ./app:/code/app
    depends_on:
      - database
    profiles:
      - alembic