# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/generated/eeg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x61pp/generated/eeg.proto"\x80\x01\n\x11\x44isplayEEGRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\x05\x12\x0e\n\x06window\x18\x02 \x01(\x05\x12\x12\n\npage_index\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x03(\t\x12\x11\n\tfile_path\x18\x05 \x01(\t\x12\x11\n\tfile_type\x18\x06 \x01(\t"_\n\x12\x44isplayEEGResponse\x12\x0e\n\x06x_data\x18\x01 \x03(\x01\x12\x13\n\x0bstimulation\x18\x02 \x03(\x05\x12$\n\x08\x64\x61tasets\x18\x03 \x03(\x0b\x32\x12.DisplayEEGDataset"t\n\x11\x44isplayEEGDataset\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07x_label\x18\x05 \x01(\x08\x12\x16\n\x0evalue_decimals\x18\x06 \x01(\x05\x32\x45\n\nEEGService\x12\x37\n\ndisplayEEG\x12\x12.DisplayEEGRequest\x1a\x13.DisplayEEGResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "app.generated.eeg_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DISPLAYEEGREQUEST._serialized_start = 28
    _DISPLAYEEGREQUEST._serialized_end = 156
    _DISPLAYEEGRESPONSE._serialized_start = 158
    _DISPLAYEEGRESPONSE._serialized_end = 253
    _DISPLAYEEGDATASET._serialized_start = 255
    _DISPLAYEEGDATASET._serialized_end = 371
    _EEGSERVICE._serialized_start = 373
    _EEGSERVICE._serialized_end = 442
# @@protoc_insertion_point(module_scope)
