"""添加回EEGdatafile

Revision ID: 0380cb81acd2
Revises: 46b22297d54e
Create Date: 2024-03-28 20:28:22.879832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0380cb81acd2'
down_revision = '46b22297d54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eegdata_file',
    sa.Column('eegdata_id', sa.Integer(), nullable=False, comment='脑电数据的id'),
    sa.Column('path', sa.Text(), nullable=False, comment='文件路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='该行是否被删除'),
    sa.ForeignKeyConstraint(['eegdata_id'], ['eegdata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='数据集文件'
    )
    op.create_index(op.f('ix_eegdata_file_eegdata_id'), 'eegdata_file', ['eegdata_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eegdata_file_eegdata_id'), table_name='eegdata_file')
    op.drop_table('eegdata_file')
    # ### end Alembic commands ###
