"""修改病人表单

Revision ID: 03b6a6104a28
Revises: dd91164fc3d8
Create Date: 2024-10-12 14:55:06.217020

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "03b6a6104a28"
down_revision = "dd91164fc3d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cohort_patient_from_data",
        "chromosome",
        existing_type=mysql.TEXT(),
        type_=sa.Integer(),
        existing_comment="染色体",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "status_after_last_chemotherapy",
        existing_type=mysql.ENUM("CR_CRi", "PR", "NR"),
        type_=sa.Integer(),
        existing_comment="末次化疗后状态",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "is_transplant",
        existing_type=mysql.TINYINT(display_width=1),
        comment="是否骨髓移植",
        existing_comment="是否复发",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "last_followup_date",
        existing_type=sa.DATE(),
        comment="末次随访日期",
        existing_comment="死亡日期",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cohort_patient_from_data",
        "last_followup_date",
        existing_type=sa.DATE(),
        comment="死亡日期",
        existing_comment="末次随访日期",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "is_transplant",
        existing_type=mysql.TINYINT(display_width=1),
        comment="是否复发",
        existing_comment="是否骨髓移植",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "status_after_last_chemotherapy",
        existing_type=sa.Integer(),
        type_=mysql.ENUM("CR_CRi", "PR", "NR"),
        existing_comment="末次化疗后状态",
        existing_nullable=True,
    )
    op.alter_column(
        "cohort_patient_from_data",
        "chromosome",
        existing_type=sa.Integer(),
        type_=mysql.TEXT(),
        existing_comment="染色体",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
