"""add DatasetFileVisualization,modify DatasetFile

Revision ID: 04ccea00786a
Revises: 2f9377b8c88e
Create Date: 2024-07-17 14:00:00.778272

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "04ccea00786a"
down_revision = "2f9377b8c88e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_file_visualization",
        sa.Column("datafile_id", sa.Integer(), nullable=False, comment="数据文件id"),
        sa.Column("umap_data_path", sa.Text(), nullable=True, comment="存储UMAP数据路径"),
        sa.Column("umap_img_path", sa.Text(), nullable=True, comment="存储UMAP图像路径"),
        sa.Column("qc_data_path", sa.Text(), nullable=True, comment="存储QC数据路径"),
        sa.Column("qc_img_path", sa.Text(), nullable=True, comment="存储QC图像路径"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["datafile_id"], ["dataset_file.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="数据集可视化文件",
    )
    op.create_index(
        op.f("ix_dataset_file_visualization_datafile_id"), "dataset_file_visualization", ["datafile_id"], unique=False
    )
    op.add_column("dataset_file", sa.Column("oss_path", sa.Text(), nullable=True, comment="oss文件路径"))
    op.add_column("dataset_file", sa.Column("file_size", sa.Float(), nullable=False, comment="文件大小"))
    op.add_column("dataset_file", sa.Column("file_format", sa.Text(), nullable=False, comment="文件格式"))
    op.add_column("dataset_file", sa.Column("other_path", sa.Text(), nullable=True, comment="其他存储路径"))
    op.add_column("dataset_file", sa.Column("backup_path", sa.Text(), nullable=True, comment="备份存储路径"))
    op.drop_column("dataset_file", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset_file", sa.Column("path", mysql.TEXT(), nullable=False, comment="文件路径"))
    op.drop_column("dataset_file", "backup_path")
    op.drop_column("dataset_file", "other_path")
    op.drop_column("dataset_file", "file_format")
    op.drop_column("dataset_file", "file_size")
    op.drop_column("dataset_file", "oss_path")
    op.drop_index(op.f("ix_dataset_file_visualization_datafile_id"), table_name="dataset_file_visualization")
    op.drop_table("dataset_file_visualization")
    # ### end Alembic commands ###
