"""添加eegdatafile orm 文件

Revision ID: 134d9c7fb6e0
Revises: a9e5944a8108
Create Date: 2024-03-27 20:55:02.096596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134d9c7fb6e0'
down_revision = 'a9e5944a8108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eegdata_file',
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='脑电数据id'),
    sa.Column('path', sa.Text(), nullable=False, comment='文件路径'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='该行是否被删除'),
    sa.ForeignKeyConstraint(['dataset_id'], ['eegdata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='脑电数据文件'
    )
    op.create_index(op.f('ix_eegdata_file_dataset_id'), 'eegdata_file', ['dataset_id'], unique=False)
    op.create_table_comment(
        'eegdata',
        '脑电数据',
        existing_comment='数据集',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'eegdata',
        '数据集',
        existing_comment='脑电数据',
        schema=None
    )
    op.drop_index(op.f('ix_eegdata_file_dataset_id'), table_name='eegdata_file')
    op.drop_table('eegdata_file')
    # ### end Alembic commands ###
