"""删除eegdatafile orm 

Revision ID: 19f8815b6a7b
Revises: 134d9c7fb6e0
Create Date: 2024-03-28 10:44:23.271929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19f8815b6a7b'
down_revision = '134d9c7fb6e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eegdata_file_dataset_id', table_name='eegdata_file')
    op.drop_table('eegdata_file')
    op.create_table_comment(
        'eegdata',
        '脑电数据',
        existing_comment='数据集',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'eegdata',
        '数据集',
        existing_comment='脑电数据',
        schema=None
    )
    op.create_table('eegdata_file',
    sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='脑电数据id'),
    sa.Column('path', mysql.TEXT(), nullable=False, comment='文件路径'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='该行是否被删除'),
    sa.Column('eegdata_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='脑电数据id'),
    sa.ForeignKeyConstraint(['dataset_id'], ['eegdata.id'], name='eegdata_file_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='脑电数据文件',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='脑电数据文件',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_eegdata_file_dataset_id', 'eegdata_file', ['dataset_id'], unique=False)
    # ### end Alembic commands ###
