"""增加dataset字段

Revision ID: 1ffdc2cfbf96
Revises: e7b61a5dfc8e
Create Date: 2024-05-09 19:46:20.404559

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1ffdc2cfbf96"
down_revision = "e7b61a5dfc8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("source", sa.Text(), nullable=True, comment="数据来源"))
    op.add_column("dataset", sa.Column("download_started_date", sa.Date(), nullable=True, comment="开始获取的日期"))
    op.add_column("dataset", sa.Column("planed_finish_date", sa.Date(), nullable=True, comment="计划完成日期"))
    op.add_column("dataset", sa.Column("contactor", sa.Text(), nullable=True, comment="联系人"))
    op.add_column("dataset", sa.Column("is_public", sa.Boolean(), nullable=True, comment="是否公开"))
    op.add_column("dataset", sa.Column("other_species", sa.Text(), nullable=True, comment="其他物种名称"))
    op.add_column("dataset", sa.Column("title", sa.Text(), nullable=True, comment="数据集名称"))
    op.drop_column("dataset", "start_acquisition_time")
    op.drop_column("dataset", "planed_acquisition_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("planed_acquisition_time", sa.DATE(), nullable=True, comment="计划完成日期"))
    op.add_column("dataset", sa.Column("start_acquisition_time", sa.DATE(), nullable=True, comment="开始获取的日期"))
    op.drop_column("dataset", "title")
    op.drop_column("dataset", "other_species")
    op.drop_column("dataset", "is_public")
    op.drop_column("dataset", "contactor")
    op.drop_column("dataset", "planed_finish_date")
    op.drop_column("dataset", "download_started_date")
    op.drop_column("dataset", "source")
    # ### end Alembic commands ###
