"""使species表拉丁名唯一

Revision ID: 22e421a98a7c
Revises: 9338b137ec12
Create Date: 2024-04-11 11:44:17.783284

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "22e421a98a7c"
down_revision = "9338b137ec12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "species",
        "latin_name",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=255),
        existing_comment="拉丁文名称",
        existing_nullable=False,
    )
    op.create_unique_constraint("uq_species_latin_name", "species", ["latin_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_species_latin_name", "species", type_="unique")
    op.alter_column(
        "species",
        "latin_name",
        existing_type=sa.String(length=255),
        type_=mysql.TEXT(),
        existing_comment="拉丁文名称",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
