"""rename File.path to name

Revision ID: 23c801a3fe36
Revises: 2047b43c9f26
Create Date: 2023-01-05 02:32:28.899671

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "23c801a3fe36"
down_revision = "2047b43c9f26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("name", sa.String(length=255), nullable=False, comment="逻辑路径"))
    op.drop_column("file", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file", sa.Column("path", mysql.VARCHAR(length=255), nullable=False, comment="逻辑路径")
    )
    op.drop_column("file", "name")
    # ### end Alembic commands ###
