"""add user and message

Revision ID: 2481c8a86f7e
Revises: 
Create Date: 2022-11-22 10:27:18.671527

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2481c8a86f7e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "gmt_create", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("msg_type", sa.String(length=20), nullable=False),
        sa.Column("creator", sa.Integer(), nullable=False),
        sa.Column("receiver", sa.Integer(), nullable=False),
        sa.Column("create_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_create_at"), "message", ["create_at"], unique=False)
    op.create_index(op.f("ix_message_receiver"), "message", ["receiver"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "gmt_create", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("staff_id", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=255), nullable=False),
        sa.Column("last_login_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_logout_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_super_user", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_message_receiver"), table_name="message")
    op.drop_index(op.f("ix_message_create_at"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
