"""update Device relation

Revision ID: 29d2c3c1dd20
Revises: 5bfa0d19bedd
Create Date: 2023-02-15 02:20:05.865739

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "29d2c3c1dd20"
down_revision = "5bfa0d19bedd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment_device",
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False, comment="实验内序号"),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"]),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.PrimaryKeyConstraint("experiment_id", "device_id"),
        comment="实验包含的设备",
    )
    op.drop_constraint("device_ibfk_1", "device", type_="foreignkey")
    op.drop_index("ix_device_experiment_id", table_name="device")
    op.drop_column("device", "index")
    op.drop_column("device", "experiment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column(
            "experiment_id", mysql.INTEGER(), autoincrement=False, nullable=False, comment="实验ID"
        ),
    )
    op.add_column(
        "device",
        sa.Column("index", mysql.INTEGER(), autoincrement=False, nullable=False, comment="实验内序号"),
    )
    op.create_foreign_key("device_ibfk_1", "device", "experiment", ["experiment_id"], ["id"])
    op.create_index("ix_device_experiment_id", "device", ["experiment_id"], unique=False)
    op.drop_table("experiment_device")
    # ### end Alembic commands ###
