"""add patients and domain

Revision ID: 36db301f4501
Revises: b49d41c2072b
Create Date: 2024-09-13 16:14:02.962099

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "36db301f4501"
down_revision = "b49d41c2072b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casbin_domain",
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="创建者id"),
        sa.Column("domain_name", sa.Text(), nullable=True, comment="policy类型"),
        sa.Column("description", sa.Text(), nullable=True, comment="domain描述"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_casbin_domain_owner_id"), "casbin_domain", ["owner_id"], unique=False)
    op.create_table(
        "cohort_patient",
        sa.Column("domain_id", sa.Integer(), nullable=False, comment="队列患者id"),
        sa.Column("patient_name", sa.Text(), nullable=False, comment="患者姓名"),
        sa.Column("gender", sa.Enum("male", "female", name="gender"), nullable=True, comment="性别"),
        sa.Column("inhospital_id", sa.Text(), nullable=False, comment="院内编号"),
        sa.Column("doctor_name", sa.Text(), nullable=True, comment="填写医生"),
        sa.Column("date_birth", sa.Date(), nullable=False, comment="出生日期"),
        sa.Column("identity_id", sa.String(length=50), nullable=True, comment="身份证编号"),
        sa.Column("hospital", sa.Text(), nullable=True, comment="就诊医院"),
        sa.Column("family_address", sa.Text(), nullable=True, comment="家庭住址"),
        sa.Column("family_address_city", sa.Text(), nullable=True, comment="家庭住址-区县"),
        sa.Column("family_address_street", sa.Text(), nullable=True, comment="家庭住址-街道"),
        sa.Column("phone_number", sa.Text(), nullable=True, comment="电话号码"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["domain_id"], ["casbin_domain.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment=" 队列患者表",
    )
    op.create_index(op.f("ix_cohort_patient_domain_id"), "cohort_patient", ["domain_id"], unique=False)
    op.create_table(
        "domain_user",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="创建者id"),
        sa.Column("domain_id", sa.Integer(), nullable=False, comment="policy类型id"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["domain_id"], ["casbin_domain.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domain_user_domain_id"), "domain_user", ["domain_id"], unique=False)
    op.create_index(op.f("ix_domain_user_user_id"), "domain_user", ["user_id"], unique=False)
    op.create_table(
        "cohort_patient_file",
        sa.Column("patient_id", sa.Integer(), nullable=False, comment="队列患者id"),
        sa.Column("oss_path", sa.Text(), nullable=True, comment="oss文件路径"),
        sa.Column("file_size", sa.Float(), nullable=False, comment="文件大小"),
        sa.Column("file_format", sa.Text(), nullable=False, comment="文件格式"),
        sa.Column("other_path", sa.Text(), nullable=True, comment="其他存储路径"),
        sa.Column("backup_path", sa.Text(), nullable=True, comment="备份存储路径"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["patient_id"], ["cohort_patient.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cohort_patient_file_patient_id"), "cohort_patient_file", ["patient_id"], unique=False)
    op.create_table(
        "cohort_patient_from_data",
        sa.Column("patient_id", sa.Integer(), nullable=False, comment="队列患者id"),
        sa.Column("timing_of_diagnosis", sa.Date(), nullable=True, comment="确诊时间"),
        sa.Column("large_classification", sa.Text(), nullable=True, comment="大分型"),
        sa.Column("small_classification", sa.Text(), nullable=True, comment="小分型"),
        sa.Column(
            "diagnose",
            sa.Enum(
                "de_no_AML",
                "sAML",
                "Ph_ALL",
                "Ph_B_ALL",
                "T_ALL",
                "ETP_ALL",
                "Ph_MPAL",
                "MLL_MPAL",
                "B_Myeloid_MPAL",
                "T_Myeloid_MPAL",
                "BPDCN",
                name="patientdiagnose",
            ),
            nullable=True,
            comment="诊断",
        ),
        sa.Column("wcb", sa.Float(), nullable=True, comment="入院时WBC（x10E9/L）"),
        sa.Column("hb", sa.Float(), nullable=True, comment="Hb（g/L）"),
        sa.Column("plt", sa.Float(), nullable=True, comment="PLT（x10E9/L）"),
        sa.Column("bone_marrow_morphology", sa.Float(), nullable=True, comment="骨髓形态"),
        sa.Column("fcm", sa.Text(), nullable=True, comment="FCM%"),
        sa.Column(
            "fusion", sa.Enum("no_test", "partial_test", "other", name="genefusion"), nullable=True, comment="融合基因"
        ),
        sa.Column("fusion_detail", sa.Text(), nullable=True, comment="融合基因详情"),
        sa.Column(
            "mutation", sa.Enum("no_test", "partial_test", "other", name="genemutation"), nullable=True, comment="基因突变"
        ),
        sa.Column("mutation_detail", sa.Text(), nullable=True, comment="基因突变详情"),
        sa.Column("chromosome", sa.Text(), nullable=True, comment="染色体"),
        sa.Column("is_therapy", sa.Boolean(), nullable=True, comment="是否治疗"),
        sa.Column("c1_date", sa.Date(), nullable=True, comment="C1治疗日期"),
        sa.Column("c1_detail", sa.Text(), nullable=True, comment="C1治疗方案"),
        sa.Column("c1_effects", sa.Enum("CR_CRi", "PR", "NR", name="ceffects"), nullable=True, comment="C1疗效评估"),
        sa.Column("c1_mrd", sa.Text(), nullable=True, comment="C1_MRD"),
        sa.Column("c2_date", sa.Date(), nullable=True, comment="C2治疗日期"),
        sa.Column("c2_detail", sa.Text(), nullable=True, comment="C2治疗方案"),
        sa.Column("c2_effects", sa.Enum("CR_CRi", "PR", "NR", name="ceffects"), nullable=True, comment="C2疗效评估"),
        sa.Column("c2_mrd", sa.Text(), nullable=True, comment="C2_MRD"),
        sa.Column("chemotherapy_counts", sa.Integer(), nullable=True, comment="化疗总程数"),
        sa.Column("last_chemotherapy_date", sa.Date(), nullable=True, comment="末次化疗日期"),
        sa.Column(
            "status_after_last_chemotherapy",
            sa.Enum("CR_CRi", "PR", "NR", name="ceffects"),
            nullable=True,
            comment="末次化疗后状态",
        ),
        sa.Column("is_relapse", sa.Boolean(), nullable=True, comment="是否复发"),
        sa.Column("cr1_date", sa.Date(), nullable=True, comment="CR1时间"),
        sa.Column("frist_relapse_date", sa.Date(), nullable=True, comment="第一次复发时间"),
        sa.Column("cr2_date", sa.Date(), nullable=True, comment="CR2时间"),
        sa.Column("second_relapse_date", sa.Date(), nullable=True, comment="第二次复发时间"),
        sa.Column("cr3_date", sa.Date(), nullable=True, comment="CR3时间"),
        sa.Column("is_transplant", sa.Boolean(), nullable=True, comment="是否复发"),
        sa.Column("transplant_date", sa.Date(), nullable=True, comment="骨髓移植时间"),
        sa.Column("is_death", sa.Boolean(), nullable=True, comment="是否死亡"),
        sa.Column("date_of_death", sa.Date(), nullable=True, comment="死亡日期"),
        sa.Column("last_followup_date", sa.Date(), nullable=True, comment="死亡日期"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["patient_id"], ["cohort_patient.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cohort_patient_from_data_patient_id"), "cohort_patient_from_data", ["patient_id"], unique=False
    )
    op.create_table(
        "cohort_patient_memo",
        sa.Column("patient_id", sa.Integer(), nullable=False, comment="队列患者id"),
        sa.Column("memo", sa.Text(), nullable=True, comment="备注内容"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["patient_id"], ["cohort_patient.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cohort_patient_memo_patient_id"), "cohort_patient_memo", ["patient_id"], unique=False)
    op.create_table(
        "domain_file",
        sa.Column("domain_id", sa.Integer(), nullable=False, comment="policy类型id"),
        sa.Column("file_id", sa.Integer(), nullable=False, comment="文件id"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["domain_id"], ["casbin_domain.id"]),
        sa.ForeignKeyConstraint(["file_id"], ["dataset_file.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domain_file_domain_id"), "domain_file", ["domain_id"], unique=False)
    op.create_index(op.f("ix_domain_file_file_id"), "domain_file", ["file_id"], unique=False)
    op.add_column("user", sa.Column("institution", sa.String(length=255), nullable=False, comment="机构"))
    op.create_index(op.f("ix_user_institution"), "user", ["institution"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_institution"), table_name="user")
    op.drop_column("user", "institution")
    op.drop_index(op.f("ix_domain_file_file_id"), table_name="domain_file")
    op.drop_index(op.f("ix_domain_file_domain_id"), table_name="domain_file")
    op.drop_table("domain_file")
    op.drop_index(op.f("ix_cohort_patient_memo_patient_id"), table_name="cohort_patient_memo")
    op.drop_table("cohort_patient_memo")
    op.drop_index(op.f("ix_cohort_patient_from_data_patient_id"), table_name="cohort_patient_from_data")
    op.drop_table("cohort_patient_from_data")
    op.drop_index(op.f("ix_cohort_patient_file_patient_id"), table_name="cohort_patient_file")
    op.drop_table("cohort_patient_file")
    op.drop_index(op.f("ix_domain_user_user_id"), table_name="domain_user")
    op.drop_index(op.f("ix_domain_user_domain_id"), table_name="domain_user")
    op.drop_table("domain_user")
    op.drop_index(op.f("ix_cohort_patient_domain_id"), table_name="cohort_patient")
    op.drop_table("cohort_patient")
    op.drop_index(op.f("ix_casbin_domain_owner_id"), table_name="casbin_domain")
    op.drop_table("casbin_domain")
    # ### end Alembic commands ###
