"""remove User.account_type

Revision ID: 469179963a6b
Revises: 8ed9dce7fe68
Create Date: 2022-11-29 06:21:06.921491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "469179963a6b"
down_revision = "8ed9dce7fe68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "account_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("account_type", mysql.VARCHAR(length=255), nullable=False)
    )
    # ### end Alembic commands ###
