"""new

Revision ID: 576fba37f0c3
Revises: 
Create Date: 2023-01-10 01:45:34.755039

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "576fba37f0c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("username", sa.String(length=255), nullable=False, comment="用户名"),
        sa.Column("hashed_password", sa.String(length=255), nullable=False, comment="密码哈希"),
        sa.Column("staff_id", sa.String(length=255), nullable=False, comment="员工号"),
        sa.Column("last_login_time", sa.DateTime(), nullable=True, comment="上次登录时间"),
        sa.Column("last_logout_time", sa.DateTime(), nullable=True, comment="上次下线时间"),
        sa.Column("access_level", sa.Integer(), nullable=False, comment="权限级别"),
        sa.PrimaryKeyConstraint("id"),
        comment="用户",
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="实验名称"),
        sa.Column(
            "type", sa.Enum("SSVEP", "MI", "neuron", name="type"), nullable=False, comment="实验类型"
        ),
        sa.Column("description", sa.Text(), nullable=False, comment="实验描述"),
        sa.Column("location", sa.String(length=255), nullable=False, comment="实验地点"),
        sa.Column("start_at", sa.DateTime(), nullable=False, comment="实验开始时间"),
        sa.Column("end_at", sa.DateTime(), nullable=False, comment="实验结束时间"),
        sa.Column("main_operator", sa.Integer(), nullable=False, comment="主操作者ID"),
        sa.Column("is_non_invasive", sa.Boolean(), nullable=True, comment="是否为无创实验"),
        sa.Column("subject_type", sa.String(length=50), nullable=True, comment="被试类型"),
        sa.Column("subject_num", sa.Integer(), nullable=True, comment="被试数量"),
        sa.Column("neuron_source", sa.String(length=50), nullable=True, comment="神经元细胞来源部位"),
        sa.Column("stimulation_type", sa.String(length=50), nullable=True, comment="刺激类型"),
        sa.Column("session_num", sa.Integer(), nullable=True, comment="实验session数量"),
        sa.Column("trail_num", sa.Integer(), nullable=True, comment="实验trail数量"),
        sa.Column("is_shared", sa.Boolean(), nullable=True, comment="实验是否公开"),
        sa.ForeignKeyConstraint(["main_operator"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="实验",
    )
    op.create_index(op.f("ix_experiment_start_at"), "experiment", ["start_at"], unique=False)
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column("type", sa.Enum("task_step_status", name="type"), nullable=False, comment="消息类型"),
        sa.Column("creator", sa.Integer(), nullable=False, comment="消息发送者ID"),
        sa.Column("receiver", sa.Integer(), nullable=False, comment="消息接收者ID"),
        sa.Column(
            "status", sa.Enum("unread", "read", name="status"), nullable=False, comment="消息状态"
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="消息内容"),
        sa.ForeignKeyConstraint(["creator"], ["user.id"]),
        sa.ForeignKeyConstraint(["receiver"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="通知",
    )
    op.create_index(
        op.f("ix_notification_gmt_create"), "notification", ["gmt_create"], unique=False
    )
    op.create_index(op.f("ix_notification_receiver"), "notification", ["receiver"], unique=False)
    op.create_table(
        "experiment_assistant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="实验助手",
    )
    op.create_index(
        op.f("ix_experiment_assistant_experiment_id"),
        "experiment_assistant",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("experiment_id", sa.Integer(), nullable=False, comment="实验ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="逻辑路径"),
        sa.Column("extension", sa.String(length=50), nullable=False, comment="文件扩展名"),
        sa.Column("index", sa.Integer(), nullable=False, comment="同一实验下的文件序号"),
        sa.Column("size", sa.Float(), nullable=False, comment="同一实验下的文件序号"),
        sa.Column("is_original", sa.Boolean(), nullable=False, comment="是否是设备产生的原始文件"),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="文件",
    )
    op.create_index(op.f("ix_file_experiment_id"), "file", ["experiment_id"], unique=False)
    op.create_index(op.f("ix_file_index"), "file", ["index"], unique=False)
    op.create_table(
        "paradigm",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("experiment_id", sa.Integer(), nullable=False, comment="实验ID"),
        sa.Column("creator", sa.Integer(), nullable=False, comment="创建者ID"),
        sa.Column("description", sa.Text(), nullable=False, comment="描述文字"),
        sa.ForeignKeyConstraint(["creator"], ["user.id"]),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="实验范式",
    )
    op.create_index(op.f("ix_paradigm_experiment_id"), "paradigm", ["experiment_id"], unique=False)
    op.create_table(
        "paradigm_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.Column("paradigm_id", sa.Integer(), nullable=False, comment="实验范式ID"),
        sa.Column("file_id", sa.Integer(), nullable=False, comment="文件ID"),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"]),
        sa.ForeignKeyConstraint(["paradigm_id"], ["paradigm.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="实验范式文件",
    )
    op.create_index(
        op.f("ix_paradigm_file_paradigm_id"), "paradigm_file", ["paradigm_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paradigm_file_paradigm_id"), table_name="paradigm_file")
    op.drop_table("paradigm_file")
    op.drop_index(op.f("ix_paradigm_experiment_id"), table_name="paradigm")
    op.drop_table("paradigm")
    op.drop_index(op.f("ix_file_index"), table_name="file")
    op.drop_index(op.f("ix_file_experiment_id"), table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_experiment_assistant_experiment_id"), table_name="experiment_assistant")
    op.drop_table("experiment_assistant")
    op.drop_index(op.f("ix_notification_receiver"), table_name="notification")
    op.drop_index(op.f("ix_notification_gmt_create"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_experiment_start_at"), table_name="experiment")
    op.drop_table("experiment")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
