"""add table human_subject_index

Revision ID: 5bfa0d19bedd
Revises: f56e34807963
Create Date: 2023-02-13 06:48:56.914514

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5bfa0d19bedd"
down_revision = "f56e34807963"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_subject_index",
        sa.Column("index", sa.Integer(), nullable=False, comment="下一个被试者的序号"),
        sa.PrimaryKeyConstraint("index"),
        comment="被试者用户序号",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("human_subject_index")
    # ### end Alembic commands ###
