"""add models

Revision ID: 5e514e211841
Revises: 469179963a6b
Create Date: 2022-12-02 02:28:32.629492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e514e211841"
down_revision = "469179963a6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmt_create", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_non_invasive", sa.Boolean(), nullable=True),
        sa.Column("subject_type", sa.String(length=50), nullable=True),
        sa.Column("subject_num", sa.Integer(), nullable=True),
        sa.Column("neuron_source", sa.String(length=50), nullable=True),
        sa.Column("stimulation_type", sa.String(length=50), nullable=True),
        sa.Column("session_num", sa.Integer(), nullable=True),
        sa.Column("trail_num", sa.Integer(), nullable=True),
        sa.Column("is_shared", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiment_operator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmt_create", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("is_main_operator", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmt_create", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("store_path", sa.String(length=511), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paradigm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmt_create", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paradigm_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmt_create", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gmt_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("paradigm_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paradigm_file")
    op.drop_table("paradigm")
    op.drop_table("file")
    op.drop_table("experiment_operator")
    op.drop_table("experiment")
    # ### end Alembic commands ###
