"""delete column File.index

Revision ID: 62708cc0b959
Revises: f55db08c038a
Create Date: 2023-02-17 02:18:15.751000

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "62708cc0b959"
down_revision = "f55db08c038a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_file_index", table_name="file")
    op.drop_column("file", "index")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column(
            "index", mysql.INTEGER(), autoincrement=False, nullable=False, comment="同一实验下的文件序号"
        ),
    )
    op.create_index("ix_file_index", "file", ["index"], unique=False)
    # ### end Alembic commands ###
