"""新建患者信息表删除修改相关字段

Revision ID: 68e0750b09f0
Revises: 36db301f4501
Create Date: 2024-09-24 13:55:23.055081

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "68e0750b09f0"
down_revision = "36db301f4501"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cohort_patient_c_therapy_detail",
        sa.Column("patient_id", sa.Integer(), nullable=False, comment="队列患者id"),
        sa.Column("c_index", sa.Integer(), nullable=True, comment="治疗次序"),
        sa.Column("c_date", sa.Date(), nullable=True, comment="治疗日期"),
        sa.Column("c_detail", sa.Text(), nullable=True, comment="治疗方案"),
        sa.Column("c_effects", sa.Enum("CR_CRi", "PR", "NR", name="ceffects"), nullable=True, comment="疗效评估"),
        sa.Column("c_mrd", sa.Text(), nullable=True, comment="MRD"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("gmt_create", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="创建时间"),
        sa.Column("gmt_modified", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="修改时间"),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="该行是否被删除"),
        sa.ForeignKeyConstraint(["patient_id"], ["cohort_patient.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cohort_patient_c_therapy_detail_patient_id"),
        "cohort_patient_c_therapy_detail",
        ["patient_id"],
        unique=False,
    )
    op.add_column(
        "cohort_patient_from_data", sa.Column("first_relapse_date", sa.Date(), nullable=True, comment="第一次复发时间")
    )
    op.drop_column("cohort_patient_from_data", "c1_mrd")
    op.drop_column("cohort_patient_from_data", "c1_date")
    op.drop_column("cohort_patient_from_data", "c2_mrd")
    op.drop_column("cohort_patient_from_data", "c2_effects")
    op.drop_column("cohort_patient_from_data", "c1_effects")
    op.drop_column("cohort_patient_from_data", "c2_detail")
    op.drop_column("cohort_patient_from_data", "c1_detail")
    op.drop_column("cohort_patient_from_data", "c2_date")
    op.drop_column("cohort_patient_from_data", "frist_relapse_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cohort_patient_from_data", sa.Column("frist_relapse_date", sa.DATE(), nullable=True, comment="第一次复发时间")
    )
    op.add_column("cohort_patient_from_data", sa.Column("c2_date", sa.DATE(), nullable=True, comment="C2治疗日期"))
    op.add_column("cohort_patient_from_data", sa.Column("c1_detail", mysql.TEXT(), nullable=True, comment="C1治疗方案"))
    op.add_column("cohort_patient_from_data", sa.Column("c2_detail", mysql.TEXT(), nullable=True, comment="C2治疗方案"))
    op.add_column(
        "cohort_patient_from_data",
        sa.Column("c1_effects", mysql.ENUM("CR_CRi", "PR", "NR"), nullable=True, comment="C1疗效评估"),
    )
    op.add_column(
        "cohort_patient_from_data",
        sa.Column("c2_effects", mysql.ENUM("CR_CRi", "PR", "NR"), nullable=True, comment="C2疗效评估"),
    )
    op.add_column("cohort_patient_from_data", sa.Column("c2_mrd", mysql.TEXT(), nullable=True, comment="C2_MRD"))
    op.add_column("cohort_patient_from_data", sa.Column("c1_date", sa.DATE(), nullable=True, comment="C1治疗日期"))
    op.add_column("cohort_patient_from_data", sa.Column("c1_mrd", mysql.TEXT(), nullable=True, comment="C1_MRD"))
    op.drop_column("cohort_patient_from_data", "first_relapse_date")
    op.drop_index(op.f("ix_cohort_patient_c_therapy_detail_patient_id"), table_name="cohort_patient_c_therapy_detail")
    op.drop_table("cohort_patient_c_therapy_detail")
    # ### end Alembic commands ###
