"""delete ParadigmFile

Revision ID: 6b9e69c519ca
Revises: a71523d0b924
Create Date: 2023-02-07 01:24:59.515488

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b9e69c519ca"
down_revision = "a71523d0b924"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paradigm_file")
    op.add_column(
        "file",
        sa.Column("paradigm_id", sa.Integer(), nullable=True, comment="范式ID，null表示不属于范式而属于实验"),
    )
    op.create_index(op.f("ix_file_paradigm_id"), "file", ["paradigm_id"], unique=False)
    op.create_foreign_key(None, "file", "paradigm", ["paradigm_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="foreignkey")
    op.drop_index(op.f("ix_file_paradigm_id"), table_name="file")
    op.drop_column("file", "paradigm_id")
    op.create_table(
        "paradigm_file",
        sa.Column("paradigm_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("file_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], name="paradigm_file_ibfk_1"),
        sa.ForeignKeyConstraint(["paradigm_id"], ["paradigm.id"], name="paradigm_file_ibfk_2"),
        sa.PrimaryKeyConstraint("paradigm_id", "file_id"),
        comment="实验范式文件关系",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_comment="实验范式文件关系",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
