"""rename Notification.msg_type to type

Revision ID: 799d16d56de0
Revises: fc6271ffa7f4
Create Date: 2022-11-28 02:57:12.220455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "799d16d56de0"
down_revision = "add4602208dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("message", "notification")
    op.add_column(
        "notification", sa.Column("type", sa.String(length=20), nullable=False)
    )
    op.drop_index("ix_message_create_at", table_name="notification")
    op.drop_index("ix_message_receiver", table_name="notification")
    op.create_index(
        op.f("ix_notification_create_at"), "notification", ["create_at"], unique=False
    )
    op.create_index(
        op.f("ix_notification_receiver"), "notification", ["receiver"], unique=False
    )
    op.drop_column("notification", "msg_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("msg_type", mysql.VARCHAR(length=20), nullable=False)
    )
    op.drop_index(op.f("ix_notification_receiver"), table_name="notification")
    op.drop_index(op.f("ix_notification_create_at"), table_name="notification")
    op.create_index("ix_message_receiver", "notification", ["receiver"], unique=False)
    op.create_index("ix_message_create_at", "notification", ["create_at"], unique=False)
    op.drop_column("notification", "type")
    op.rename_table("notification", "message")
    # ### end Alembic commands ###
