"""add device table

Revision ID: 86c548e3656b
Revises: 6b9e69c519ca
Create Date: 2023-02-07 03:41:02.421461

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "86c548e3656b"
down_revision = "6b9e69c519ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("experiment_id", sa.Integer(), nullable=False, comment="实验ID"),
        sa.Column("brand", sa.String(length=255), nullable=False, comment="设备品牌"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="设备名称"),
        sa.Column("purpose", sa.String(length=255), nullable=False, comment="设备用途"),
        sa.Column("index", sa.Integer(), nullable=False, comment="实验内序号"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="实验设备",
    )
    op.create_index(op.f("ix_device_experiment_id"), "device", ["experiment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_experiment_id"), table_name="device")
    op.drop_table("device")
    # ### end Alembic commands ###
