"""删除eegdatafile 表

Revision ID: 8df725131837
Revises: 0380cb81acd2
Create Date: 2024-03-29 13:59:32.954948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8df725131837'
down_revision = '0380cb81acd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('ix_eegdata_file_eegdata_id', table_name='eegdata_file',type_='foreignkey')
    # op.drop_index('ix_eegdata_file_eegdata_id', table_name='eegdata_file')
    op.drop_table('eegdata_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eegdata_file',
    sa.Column('eegdata_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='脑电数据的id'),
    sa.Column('path', mysql.TEXT(), nullable=False, comment='文件路径'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='该行是否被删除'),
    sa.ForeignKeyConstraint(['eegdata_id'], ['eegdata.id'], name='eegdata_file_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据集文件',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='数据集文件',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_eegdata_file_eegdata_id', 'eegdata_file', ['eegdata_id'], unique=False)
    # ### end Alembic commands ###
