"""增加species表

Revision ID: 9338b137ec12
Revises: fc790ff29f0a
Create Date: 2024-04-10 19:16:39.604826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9338b137ec12'
down_revision = 'fc790ff29f0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('Chinese_name', sa.Text(), nullable=False, comment='中文名称'),
    sa.Column('English_name', sa.Text(), nullable=False, comment='英文名称'),
    sa.Column('latin_name', sa.Text(), nullable=False, comment='拉丁文名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='该行是否被删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='物种名称'
    )
    op.alter_column('eeg_data', 'data_update_year',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_comment='数据上传时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eeg_data', 'data_update_year',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_comment='数据上传时间',
               existing_nullable=False)
    op.drop_table('species')
    # ### end Alembic commands ###
