"""remove Notification.create_at

Revision ID: a263973ef3a5
Revises: ce94f9410241
Create Date: 2022-12-08 09:25:31.679926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a263973ef3a5'
down_revision = 'ce94f9410241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_create_at', table_name='notification')
    op.drop_column('notification', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('create_at', mysql.DATETIME(), nullable=False))
    op.create_index('ix_notification_create_at', 'notification', ['create_at'], unique=False)
    # ### end Alembic commands ###
