"""rename ExperimentHumanSubject.human_subject_id to user_id

Revision ID: a56d2739dd47
Revises: b2cdea1cb44f
Create Date: 2023-02-10 02:01:17.289826

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a56d2739dd47"
down_revision = "b2cdea1cb44f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("experiment_human_subject", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "experiment_human_subject_ibfk_2", "experiment_human_subject", type_="foreignkey"
    )
    op.create_foreign_key(None, "experiment_human_subject", "user", ["user_id"], ["id"])
    op.drop_column("experiment_human_subject", "human_subject_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiment_human_subject",
        sa.Column("human_subject_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "experiment_human_subject", type_="foreignkey")
    op.create_foreign_key(
        "experiment_human_subject_ibfk_2",
        "experiment_human_subject",
        "human_subject",
        ["human_subject_id"],
        ["id"],
    )
    op.drop_column("experiment_human_subject", "user_id")
    # ### end Alembic commands ###
