"""增加EEGdata字段

Revision ID: a9e5944a8108
Revises: a0d93a525a2a
Create Date: 2024-03-27 14:35:46.708272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e5944a8108'
down_revision = 'a0d93a525a2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eegdata',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False, comment='性别'),
    sa.Column('age', sa.Integer(), nullable=False, comment='年龄'),
    sa.Column('data_update_year', sa.DateTime(), nullable=False, comment='数据上传时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('gmt_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('gmt_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='修改时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='该行是否被删除'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='数据集'
    )
    op.create_index(op.f('ix_eegdata_user_id'), 'eegdata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eegdata_user_id'), table_name='eegdata')
    op.drop_table('eegdata')
    # ### end Alembic commands ###
