"""add task & taskstep

Revision ID: ab777f6a22c8
Revises: 62708cc0b959
Create Date: 2023-03-16 08:58:37.168008

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ab777f6a22c8"
down_revision = "62708cc0b959"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("experiment_id", sa.Integer(), nullable=False, comment="实验ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="任务名"),
        sa.Column("description", sa.Text(), nullable=False, comment="任务描述"),
        sa.Column("source_file", sa.Integer(), nullable=False, comment="任务分析的文件ID"),
        sa.Column(
            "type",
            sa.Enum("preprocess", "analysis", "preprocess_analysis", name="tasktype"),
            nullable=False,
            comment="任务类型",
        ),
        sa.Column("start_at", sa.DateTime(), nullable=True, comment="任务开始执行的时间"),
        sa.Column("end_at", sa.DateTime(), nullable=True, comment="任务结束时间"),
        sa.Column(
            "status",
            sa.Enum("wait_start", "running", "done", "error", "cancelled", name="taskstatus"),
            nullable=False,
            comment="任务状态",
        ),
        sa.Column("creator", sa.Integer(), nullable=False, comment="任务创建者ID"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.ForeignKeyConstraint(["creator"], ["user.id"]),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"]),
        sa.ForeignKeyConstraint(["source_file"], ["file.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="任务",
    )
    op.create_index(op.f("ix_task_experiment_id"), "task", ["experiment_id"], unique=False)
    op.create_table(
        "task_step",
        sa.Column("task_id", sa.Integer(), nullable=False, comment="任务ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="步骤名字"),
        sa.Column(
            "type",
            sa.Enum("preprocess", "analysis", name="tasksteptype"),
            nullable=False,
            comment="任务步骤类型",
        ),
        sa.Column("parameter", sa.Text(), nullable=False, comment="步骤参数JSON"),
        sa.Column("index", sa.Integer(), nullable=False, comment="任务中的步骤顺序"),
        sa.Column(
            "status",
            sa.Enum("wait_start", "running", "done", "error", "cancelled", name="taskstatus"),
            nullable=False,
            comment="步骤状态",
        ),
        sa.Column("start_at", sa.DateTime(), nullable=True, comment="步骤开始执行的时间"),
        sa.Column("end_at", sa.DateTime(), nullable=True, comment="步骤结束时间"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column(
            "gmt_create",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "gmt_modified",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="修改时间",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="该行是否被删除",
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
        comment="任务步骤",
    )
    op.create_index(op.f("ix_task_step_task_id"), "task_step", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_step_task_id"), table_name="task_step")
    op.drop_table("task_step")
    op.drop_index(op.f("ix_task_experiment_id"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
