"""add choices on message.status

Revision ID: add4602208dd
Revises: 2481c8a86f7e
Create Date: 2022-11-22 15:01:08.100532

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "add4602208dd"
down_revision = "2481c8a86f7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message", "status", existing_type=mysql.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "message", "status", existing_type=mysql.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###
