"""init mysql

Revision ID: bccf9dde4e2d
Revises: 
Create Date: 2022-11-18 09:22:03.473380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bccf9dde4e2d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
