"""add paradigm.creator

Revision ID: ce94f9410241
Revises: c30c0806827f
Create Date: 2022-12-07 01:48:48.233955

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ce94f9410241"
down_revision = "c30c0806827f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paradigm", sa.Column("creator", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paradigm", "creator")
    # ### end Alembic commands ###
