"""modify ModelMixin defaults

Revision ID: d89c819e9f78
Revises: add4602208dd
Create Date: 2022-11-24 16:00:33.291454

"""

# revision identifiers, used by Alembic.
revision = "d89c819e9f78"
down_revision = "add4602208dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
