"""修改c_therapy_index字段

Revision ID: dd91164fc3d8
Revises: 68e0750b09f0
Create Date: 2024-09-26 14:41:53.390710

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "dd91164fc3d8"
down_revision = "68e0750b09f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cohort_patient_c_therapy_detail",
        "c_index",
        existing_type=mysql.INTEGER(),
        nullable=False,
        existing_comment="治疗次序",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cohort_patient_c_therapy_detail",
        "c_index",
        existing_type=mysql.INTEGER(),
        nullable=True,
        existing_comment="治疗次序",
    )
    # ### end Alembic commands ###
