"""disable unique on user.username

Revision ID: f55db08c038a
Revises: 29d2c3c1dd20
Create Date: 2023-02-16 06:24:33.247737

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f55db08c038a"
down_revision = "29d2c3c1dd20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_index(op.f("ix_user_staff_id"), "user", ["staff_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_staff_id"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###
