"""alter ExperimentHumanSubject

Revision ID: f56e34807963
Revises: a56d2739dd47
Create Date: 2023-02-10 09:28:01.563337

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f56e34807963"
down_revision = "a56d2739dd47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "experiment_human_subject_ibfk_2", "experiment_human_subject", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "experiment_human_subject", "human_subject", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "experiment_human_subject", type_="foreignkey")
    op.create_foreign_key(
        "experiment_human_subject_ibfk_2", "experiment_human_subject", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
