"""修改eegdatafilez表字段id

Revision ID: f8c2dd179c39
Revises: 134d9c7fb6e0
Create Date: 2024-03-28 09:13:19.940725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8c2dd179c39'
down_revision = '134d9c7fb6e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eegdata_file', sa.Column('eegdata_id', sa.Integer(), nullable=False, comment='脑电数据id'))
    op.drop_index('ix_eegdata_file_dataset_id', table_name='eegdata_file')
    op.create_index(op.f('ix_eegdata_file_eegdata_id'), 'eegdata_file', ['eegdata_id'], unique=False)
    op.drop_constraint('eegdata_file_ibfk_1', 'eegdata_file', type_='foreignkey')
    op.create_foreign_key(None, 'eegdata_file', 'eegdata', ['eegdata_id'], ['id'])
    op.drop_column('eegdata_file', 'dataset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eegdata_file', sa.Column('dataset_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='脑电数据id'))
    op.drop_constraint(None, 'eegdata_file', type_='foreignkey')
    op.create_foreign_key('eegdata_file_ibfk_1', 'eegdata_file', 'eegdata', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_eegdata_file_eegdata_id'), table_name='eegdata_file')
    op.create_index('ix_eegdata_file_dataset_id', 'eegdata_file', ['dataset_id'], unique=False)
    op.drop_column('eegdata_file', 'eegdata_id')
    # ### end Alembic commands ###
