- entity_id: user
  zh_CN: 用户
  en_US: user

- entity_id: file
  zh_CN: 文件
  en_US: file

- entity_id: experiment
  zh_CN: 实验
  en_US: experiment

- entity_id: device
  zh_CN: 设备
  en_US: device

- entity_id: human subject
  zh_CN: 被试者
  en_US: human subject

- entity_id: task
  zh_CN: 任务
  en_US: task

- entity_id: paradigm
  zh_CN: 范式
  en_US: paradigm
