- entity_id: user
  zh-CN: 用户
  en-US: user

- entity_id: file
  zh-CN: 文件
  en-US: file

- entity_id: experiment
  zh-CN: 实验
  en-US: experiment

- entity_id: device
  zh-CN: 设备
  en-US: device

- entity_id: human subject
  zh-CN: 被试者
  en-US: human subject

- entity_id: task
  zh-CN: 任务
  en-US: task

- entity_id: paradigm
  zh-CN: 范式
  en-US: paradigm

- entity_id: atlas
  zh-CN: 脑图谱
  en-US: atlas

- entity_id: atlas_region
  zh-CN: 脑图谱区域
  en-US: atlas region

- entity_id: atlas_region_link
  zh-CN: 脑图谱区域连接
  en-US: atlas region link

- entity_id: atlas_behavioral_domain
  zh-CN: 脑图谱行为域
  en-US: atlas behavioral domain

- entity_id: atlas_paradigm_class
  zh-CN: 脑图谱范例集
  en-US: atlas paradigm class

- entity_id: dataset
  zh-CN: 数据集
  en-US: dataset

- entity_id: dataset_file
  zh-CN: 数据集文件
  en-US: dataset file

- entity_id: eeg_data
  zh-CN: 脑电数据
  en-US: eeg data

- entity_id: species
  zh-CN: 物种
  en-US: species