# 成功
- message_id: success
  zh_CN: 成功
  en_US: success

# 400 错误

- message_id: params error
  zh_CN: '参数错误: {}'
  en_US: 'params error: {}'

- message_id: page not found
  zh_CN: '没有该页面: {}'
  en_US: 'page not found: {}'

- message_id: not found
  zh_CN: '{}不存在'
  en_US: '{} cannot be found'

# 401 错误

- message_id: not login
  zh_CN: 用户未登录
  en_US: user doesn't login

- message_id: wrong password
  zh_CN: 密码错误
  en_US: wrong password

- message_id: no enough access level
  zh_CN: 用户权限不足
  en_US: user doesn't have enough access level

- message_id: session timeout
  zh_CN: 会话已过期，请重新登录
  en_US: session timeout, please login

- message_id: file type not supported
  zh_CN: '{}不是支持的文件类型'
  en_US: '{} is not supported file type'

# 500 错误

- message_id: inner server error
  zh_CN: '服务端错误: {}'
  en_US: 'inner server error: {}'

- message_id: remote service error
  zh_CN: '远程服务错误: {}'
  en_US: 'remote service error: {}'
