version: "3.8"
services:
  cache:
    image: ${IMAGE_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
    healthcheck:
      test: redis-cli ping || exit 1
