version: "3.8"
services:
  database:
    image: ${IMAGE_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai
    ports:
      - "8100:3306"
    volumes:
      - ~/mysql/ZJBrainSciencePlatform/data:/var/lib/mysql
      - ~/mysql/ZJBrainSciencePlatform/backup:/backup
      - ~/log/ZJBrainSciencePlatform/mysql:/var/log/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
