version: "3"
services:
  platform:
    image: ${PLATFORM_IMAGE_TAG}
    ports:
      - "1919:80"
    environment:
      LOG_ROOT: /log
      FILE_ROOT: /file
      DATABASE_URL: ${DATABASE_URL}
      ALGORITHM_HOST: algorithm
      CACHE_HOST: cache
      CACHE_PORT: 6379
    volumes:
      - /data/ZJBrainSciencePlatform/data/file:/file
      - /data/ZJBrainSciencePlatform/log/platform:/log
      - ../..:/code
    restart: always
    depends_on:
      - database
      - cache
    healthcheck:
      test: curl --fail http://localhost/openapi.json || exit 1

  database:
    image: ${DATABASE_IMAGE_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai
    ports:
      - "8100:3306"
    volumes:
      - /data/ZJBrainSciencePlatform/mysql/data:/var/lib/mysql
      - /data/ZJBrainSciencePlatform/mysql/backup:/backup
      - /data/ZJBrainSciencePlatform/mysql/log:/var/log/mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost || exit 1

  cache:
    image: ${CACHE_IMAGE_TAG}
    ports:
      - "8200:6379"
    restart: always
    healthcheck:
      test: redis-cli ping

  file-server:
    image: ${FILE_SERVER_IMAGE_TAG}
    ports:
      - "8300:80"
    environment:
      ZJBS_FILE_FILE_DIR: /data/file
      ZJBS_FILE_LOG_DIR: /data/log
    volumes:
      - ${FILE_DIR:-/data/ZJBrainSciencePlatform/file_server/file}:/data/file
      - ${LOG_DIR:-/data/ZJBrainSciencePlatform/file_server/log}:/data/log
    healthcheck:
      test: curl --fail http://localhost/openapi.json || exit 1
