version: "3.8"
services:

  platform:
    image: ${IMAGE_TAG}
    ports:
      - "1919:80"
    environment:
      LOG_ROOT: /log
      FILE_ROOT: /file
      DATABASE_URL: mysql+pymysql://zjlab:zjlab2022@database:3306/zj_brain_science_platform
      ALGORITHM_HOST: algorithm
      CACHE_HOST: cache
      CACHE_PORT: 6379
      FILE_SERVER_URL: http://file-server
    volumes:
      - /data/ZJBrainSciencePlatform/data/file:/file
      - /data/ZJBrainSciencePlatform/log/platform:/log
    deploy:
      replicas: ${REPLICAS}
      restart_policy:
        condition: any
        delay: 10s
    healthcheck:
      test: curl --fail http://localhost/openapi.json || exit 1
