name: Pytest测试

on:
  push:
    branches:
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      DEBUG_MODE: on
      LOG_ROOT: ~/log
      FILE_ROOT: ~/file

    services:
      cache:
        image: redis:7.0
        ports:
          - 8200:6379
      database:
        image: zjlabbrainscience/zj-brain-science-platform-database:latest
        ports:
          - 8100:3306
        env:
          MYSQL_ROOT_PASSWORD: zjlab2022root
          MYSQL_USER: zjlab
          MYSQL_PASSWORD: zjlab2022
          MYSQL_DATABASE: zj_brain_science_platform
          TZ: Asia/Shanghai

    steps:

      - name: 切换到dev分支
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: 安装Poetry
        run: pipx install poetry

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry

      - name: 安装依赖项
        run: poetry install --with test

      - name: 创建文件夹
        run: mkdir -p ~/log ~/file

      - name: 运行alembic
        run: poetry run alembic upgrade head

      - name: 运行Pytest
        run: poetry run pytest
