name: Pytest测试

on:
  push:
    branches:
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: 切换到dev分支
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: 安装Poetry
        run: pipx install poetry

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry

      - name: 安装依赖项
        run: poetry install --with test

      - name: 创建文件夹
        shell: bash
        run: |
          dirs=("$HOME/log/ZJBrainSciencePlatform/app" "$HOME/data/ZJBrainSciencePlatform/file" /data/ZJBrainSciencePlatform/mysql/data /data/ZJBrainSciencePlatform/mysql/backup /data/ZJBrainSciencePlatform/mysql/log)
          username="$(id -nu)"
          userGroup="$(id -ng)"
          sudo mkdir -p "${dirs[@]}" 
          sudo chown -R "${username}:${userGroup}" "${dirs[@]}"

      - name: 启动database
        shell: bash
        run: |
          export COMPOSE_PROJECT_NAME=platform
          export IMAGE_TAG=zjlabbrainscience/zj-brain-science-platform-database
          docker compose --file ./deploy/compose/database.compose.yaml up --detach

      - name: 启动cache
        shell: bash
        run: |
          export COMPOSE_PROJECT_NAME=platform
          export IMAGE_TAG=redis:7.0
          docker compose --file ./deploy/compose/cache.compose.yaml up --detach


      - name: 运行alembic
        run: poetry run alembic upgrade head

      - name: 运行Pytest
        run: poetry run pytest
